name: Lint
on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    strategy:
      matrix:
        include:
          - name: Detekt
            task: "reportMerge detektDebug detektDebugAndroidTest detektDebugUnitTest detektMain detektMainAndroid detektMainJvm detektRelease detektTest detektTestJvm --continue"
            sarif_file: "build/reports/detekt/merge.sarif"
            category: "detekt"
          - name: Detekt (build-logic)
            task: ":build-logic:detektMain"
            sarif_file: "build-logic/build/reports/detekt/main.sarif"
            category: "detekt"
          - name: Android Lint Debug
            task: ":sample:androidApp:lintDebug"
            sarif_file: "sample/androidApp/build/reports/lint-results-debug.sarif"
            category: "android-lint"
          - name: android Lint Release
            task: ":sample:androidApp:lintRelease"
            sarif_file: "sample/androidApp/build/reports/lint-results-release.sarif"
            category: "android-lint"
    name: 🔍️ ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
          cmake-version: '4.1.2'
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@40e4de17368d864bbd6f9810508abd31502b4bde # main
      - name: 🔍️Run analyze ${{ matrix.name }}
        run: ./gradlew ${{ matrix.task }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        if: ${{ !cancelled()}}
        with:
          sarif_file: ${{ matrix.sarif_file }}
          category: ${{ matrix.category }}
