name: Test

on:
  workflow_call:

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
          cmake-version: '4.1.2'
      - name: Setup Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: '5.0.7'
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@main
      - name: Run Unit Tests
        run: ./gradlew jvmTest testAndroidHostTest jsNodeTest wasmJsTest wasmJsNodeTest --continue
      - name: Upload Test Report
        if: cancelled() != true
        uses: dorny/test-reporter@v3
        with:
          name: 'Unit Test'
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: 'java-junit'
          fail-on-error: false

  ios-test:
    name: iOS Test
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
          cmake-version: '4.1.2'
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@main
      - name: Run iOS Simulator Tests
        run: ./gradlew :kioarch:iosSimulatorArm64Test --continue
      - name: Upload Test Report
        if: cancelled() != true
        uses: dorny/test-reporter@v3
        with:
          name: 'iOS Test'
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: 'java-junit'
          fail-on-error: false

  instrumentation-test:
    name: Instrumentation Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@main
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: AVD cache
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-35
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: default
          arch: x86_64
          profile: pixel_7_pro
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Run Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: default
          arch: x86_64
          profile: pixel_7_pro
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest --continue
          cmake: '4.1.2'
      - name: Upload Test Report
        if: cancelled() != true
        uses: dorny/test-reporter@v3
        with:
          name: 'Instrumentation Test'
          path: '**/build/outputs/*Test-results/**/TEST-*.xml'
          reporter: 'java-junit'
          fail-on-error: false
